import { ReactNode } from "react"
import { Metadata } from "next"
import { Inter } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs"
import { dark } from "@clerk/themes"

import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Auth',
    description: 'Generated by create next app'
}

export default function RootLayout ({ 
    children 
}: { 
    children: ReactNode 
}) {
    return(
        <ClerkProvider appearance={{ baseTheme: dark }}>
            <html lang="en" suppressHydrationWarning>
                <body className={`${inter.className} bg-[#000000]`}>
                    <div className="w-full flex items-center justify-center min-h-screen">
                        {children}
                    </div>
                </body>
            </html>
        </ClerkProvider>
    )
}